services:
  tomcat-cont:
    container_name: tomcatInstance
    build: .
    ports:
      - "8082:8080"
    volumes:
      - ./logs:/usr/local/tomcat/logs
    restart: always 
    networks:
      - tomcat_network
    
networks:
  tomcat_network:
    driver: bridge