---
- name: Install Docker on Ubuntu 
  hosts: web1
  become: true  
  tasks:
    - name: Update apt package 
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages for Docker installation
      ansible.builtin.apt:
        name:
          - curl
          - sudo
        state: present

    - name: Create keyring directory for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to Apt sources
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list  # Prevent re-running if already added

    - name: Update apt package again to include Docker packages
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker and Docker Compose without any prompts
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        force: yes

    - name: Ensure Docker service is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes


    - name: Ensure Docker service is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes


    # Define Docker image and container variables
    - name: Set Docker image and container variables
      ansible.builtin.set_fact:
        docker_image: "susanstha17/finalproj"  # Replace with your image name
        docker_tag: "v1.3"  # Replace with your tag
        container_name: "devopsproj"  # Replace with your container name

    # Pull Docker image from Docker Hub or local registry
    - name: Pull image from Docker Hub or local registry
      community.docker.docker_image:
        name: "susanstha17/finalproj"  # Example: susanstha/devopsweather
        tag: "v1.3"  # Example: v1.3
        source: pull
      register: docker_pull_result

    - name: Show status of Docker image pull
      ansible.builtin.debug:
        msg: "Docker image {{ docker_image }} was pulled. Status: {{ docker_pull_result.changed }}"

    - name: Run Docker container from pulled image
      community.docker.docker_container:
        name: "devopsproj"  # "devopsweather_container"
        image: "susanstha17/finalproj:v1.3"  # "susanstha/devopsweather:v1.2"
        state: started
        restart_policy: always
        ports:
          - "8082:8080"